### PR TITLE
Search for source files in other directories too

### PR DESCRIPTION
**Pull request by arcusfelis**
This would solve an empty file name when code is not in the default directory (for example, code is in test/ directory).

Why do we wanna tests in the cover report?
This is optional and disabled by default.
But you wanna enable it to show uncalled testcases or helper functions, for example. It allows to find dead code in the test suites.

### CODE REVIEW

**Review by NelsonVides — COMMENTED** [review]
Shouldn't we want this to be maybe a flag? So that we can make sure we don't accidentally mix files from one dir or another? How would you expect to use this in a project?

**Comment by arcusfelis** [comment]
@NelsonVides I don't think it should be a flag.
It only handles case when without this fix `codecov.json` would have an entry with an empty filename.
And such entry would just crash codecov site anyway (i.e. no empty filename is not allowed, such code report is invalid).

so, we scan first `src/` like the old version.
if code not found in `src/` - we scan whole project, except stuff in `_build` directory (i.e. copies of our files and deps).

Passing flags would make code harder to read.


Use case: to see dead code in test suites. I.e. https://github.com/esl/cets/pull/7/files#diff-61faf9f90a98df6672211f2fafabe612cc7dfc5cd82659375709997851cd39a8

But we have a loooot of dead code in MIM test suites for sure :D

Ah, yea, only code in `src/` is covered by default, so to collect cover in other directories you need to pass them in `src_dirs` (i.e. `{src_dirs, ["src", "test"]}`).

i.e. I don't think it would break any of existing integrations, because it changes the behaviour, when by this point report is already broken (i.e. an empty name case).

But yea, if there are two files in the project with the same name, which are not in `src/` directory - we would set an invalid empty string again, as before :D Oh, now I think MIM uses `big_tests/_build`, so filtering out from `_build` will not work.

(i.e. I probably should just use `src_dirs` option from rebar3 config).

**Comment by arcusfelis** [comment]
OK, i've patched and now we use `src_dirs` to find code.
We scan each directory.

And we use the old behaviour when `src_dirs` option is not provided.

**Review by NelsonVides — APPROVED** [review]
Ooooh ok, that looks a lot better now.

**Pull request merged**
